-- ==============================================================================
-- BUCHISAPA BURGER & BROASTER - ESQUEMA Y MIGRACION COMPLETA PARA SUPABASE
-- Disenado para soportar 100% el Panel de Administracion (Admin), Tienda y Pedidos
-- Preserva exactamente los IDs de Platos (PL0001-PL0057), Categorias (C0001-C0010),
-- Portadas, Promociones, Perfiles de Administrador y Pedidos en tiempo real.
--
-- Ejecuta este script en: Supabase Dashboard -> SQL Editor -> New Query -> Run
-- ==============================================================================

-- 1. Habilitar extension UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLA: CATEGORIAS (categories) - Preserva IDs 'C0001' a 'C0010'
CREATE TABLE IF NOT EXISTS public.categories (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL,
    name TEXT NOT NULL,
    image TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABLA: PRODUCTOS / PLATOS (products) - Preserva IDs 'PL0001' a 'PL0057' (y auto-incremento 'PL0058'...)
CREATE TABLE IF NOT EXISTS public.products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category_id TEXT REFERENCES public.categories(id) ON DELETE SET NULL,
    category TEXT,
    price NUMERIC(10,2) NOT NULL DEFAULT 0,
    description TEXT,
    available BOOLEAN DEFAULT true,
    stock INTEGER DEFAULT 50,
    image TEXT,
    includes_sauces BOOLEAN DEFAULT false,
    accompaniments JSONB DEFAULT '[]'::jsonb,
    cremas JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABLA: PROMOCIONES (promotions) - Preserva IDs 'promo-1' a 'promo-4'
CREATE TABLE IF NOT EXISTS public.promotions (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    price NUMERIC(10,2) NOT NULL DEFAULT 0,
    original_price NUMERIC(10,2),
    image TEXT,
    badge TEXT,
    active BOOLEAN DEFAULT true,
    order_num INTEGER DEFAULT 0,
    features JSONB DEFAULT '[]'::jsonb,
    accompaniments JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. TABLA: BANNERS / PORTADAS HERO (portadas) - Preserva IDs 'portada-1' a 'portada-5'
CREATE TABLE IF NOT EXISTS public.portadas (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    highlight TEXT,
    subtitle TEXT,
    badge TEXT,
    badge_type TEXT,
    image TEXT NOT NULL,
    image_mobile TEXT,
    button_text TEXT,
    button_category TEXT,
    features JSONB DEFAULT '[]'::jsonb,
    active BOOLEAN DEFAULT true,
    order_num INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. TABLA: PEDIDOS Y COMANDAS (orders) - Sincronizado con Panel de Pedidos y KDS Cocina
CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY,
    order_number TEXT NOT NULL,
    order_code TEXT,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_email TEXT,
    order_type TEXT NOT NULL DEFAULT 'pickup',
    delivery_address TEXT,
    delivery_reference TEXT,
    table_number TEXT,
    payment_method TEXT NOT NULL DEFAULT 'efectivo',
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'pendiente',
    subtotal NUMERIC(10,2) DEFAULT 0,
    delivery_fee NUMERIC(10,2) DEFAULT 0,
    total NUMERIC(10,2) NOT NULL DEFAULT 0,
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    user_id TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. TABLA: LIBRO DE RECLAMACIONES (claims)
CREATE TABLE IF NOT EXISTS public.claims (
    id TEXT PRIMARY KEY,
    full_name TEXT NOT NULL,
    doc_type TEXT NOT NULL DEFAULT 'DNI',
    doc_number TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    address TEXT,
    claim_type TEXT NOT NULL DEFAULT 'reclamo',
    amount NUMERIC(10,2) DEFAULT 0,
    description TEXT NOT NULL,
    consumer_claim TEXT,
    status TEXT NOT NULL DEFAULT 'pendiente',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. TABLA: PERFILES DE USUARIO Y CLIENTES (perfiles) - Vista de Clientes del Panel Admin
CREATE TABLE IF NOT EXISTS public.perfiles (
    id TEXT PRIMARY KEY,
    uid TEXT UNIQUE,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    phone TEXT,
    doc_type TEXT DEFAULT 'DNI',
    doc_number TEXT,
    role TEXT DEFAULT 'customer',
    is_admin BOOLEAN DEFAULT false,
    email_verified BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. TABLA: CONFIGURACION GENERAL DEL NEGOCIO (configuracion)
CREATE TABLE IF NOT EXISTS public.configuracion (
    id TEXT PRIMARY KEY DEFAULT 'principal',
    business_name TEXT NOT NULL DEFAULT 'BuchiSapa Burger & Broaster',
    ruc TEXT DEFAULT '10723456781',
    address TEXT DEFAULT 'Jr. San Martin 456, Tarapoto, San Martin, Peru',
    phone TEXT DEFAULT '+51 942 475 459',
    email TEXT DEFAULT 'buchisapaweb@gmail.com',
    delivery_fee NUMERIC(10,2) DEFAULT 3.00,
    printer_ip TEXT DEFAULT '192.168.8.100',
    printer_port INTEGER DEFAULT 80,
    opening_hours TEXT DEFAULT 'Lunes a Domingo: 5:00 PM - 11:30 PM',
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- INDICES DE ALTO RENDIMIENTO
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_code ON public.products(code);
CREATE INDEX IF NOT EXISTS idx_products_popular ON public.products(popular);
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON public.orders(customer_email);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_perfiles_role ON public.perfiles(role);
CREATE INDEX IF NOT EXISTS idx_perfiles_email ON public.perfiles(email);

-- 10. POLITICAS DE SEGURIDAD (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracion ENABLE ROW LEVEL SECURITY;

-- Permisos completos para lectura y operaciones del panel y tienda
DROP POLICY IF EXISTS "Categorias publicas" ON public.categories;
CREATE POLICY "Categorias publicas" ON public.categories FOR ALL USING (true);

DROP POLICY IF EXISTS "Productos publicos" ON public.products;
CREATE POLICY "Productos publicos" ON public.products FOR ALL USING (true);

DROP POLICY IF EXISTS "Promociones publicas" ON public.promotions;
CREATE POLICY "Promociones publicas" ON public.promotions FOR ALL USING (true);

DROP POLICY IF EXISTS "Portadas publicas" ON public.portadas;
CREATE POLICY "Portadas publicas" ON public.portadas FOR ALL USING (true);

DROP POLICY IF EXISTS "Pedidos publicos" ON public.orders;
CREATE POLICY "Pedidos publicos" ON public.orders FOR ALL USING (true);

DROP POLICY IF EXISTS "Reclamaciones publicas" ON public.claims;
CREATE POLICY "Reclamaciones publicas" ON public.claims FOR ALL USING (true);

DROP POLICY IF EXISTS "Perfiles publicos" ON public.perfiles;
CREATE POLICY "Perfiles publicos" ON public.perfiles FOR ALL USING (true);

DROP POLICY IF EXISTS "Configuracion publica" ON public.configuracion;
CREATE POLICY "Configuracion publica" ON public.configuracion FOR ALL USING (true);

-- ==============================================================================
-- 11. INSERCION DE TODOS LOS DATOS CON SUS IDS EXACTOS
-- ==============================================================================

-- A. CATEGORIAS OFICIALES (10) - IDs: C0001 a C0010
INSERT INTO public.categories (id, slug, name, image) VALUES ('C0001', 'promociones', 'PROMOCIONES', 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop&q=80') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, name = EXCLUDED.name, image = EXCLUDED.image;
INSERT INTO public.categories (id, slug, name, image) VALUES ('C0002', 'alitas', 'ALITAS', '/imagenes/categorias/alitas/banner.webp') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, name = EXCLUDED.name, image = EXCLUDED.image;
INSERT INTO public.categories (id, slug, name, image) VALUES ('C0003', 'bebidas', 'BEBIDAS', '/imagenes/categorias/bebidas/banner.webp') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, name = EXCLUDED.name, image = EXCLUDED.image;
INSERT INTO public.categories (id, slug, name, image) VALUES ('C0004', 'broaster', 'BROASTER', '/imagenes/categorias/broaster/banner.webp') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, name = EXCLUDED.name, image = EXCLUDED.image;
INSERT INTO public.categories (id, slug, name, image) VALUES ('C0005', 'hamburguesas', 'HAMBURGUESAS', '/imagenes/categorias/hamburguesas/banner.webp') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, name = EXCLUDED.name, image = EXCLUDED.image;
INSERT INTO public.categories (id, slug, name, image) VALUES ('C0006', 'infusiones', 'INFUSIONES', '/imagenes/categorias/infusiones/banner.webp') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, name = EXCLUDED.name, image = EXCLUDED.image;
INSERT INTO public.categories (id, slug, name, image) VALUES ('C0007', 'platos-amazonicos', 'PLATOS AMAZÓNICOS', '/imagenes/categorias/platos-amazonicos/banner.webp') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, name = EXCLUDED.name, image = EXCLUDED.image;
INSERT INTO public.categories (id, slug, name, image) VALUES ('C0008', 'refrescos', 'REFRESCOS', '/imagenes/categorias/refrescos/banner.webp') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, name = EXCLUDED.name, image = EXCLUDED.image;
INSERT INTO public.categories (id, slug, name, image) VALUES ('C0009', 'salchipapas', 'SALCHIPAPAS Y SALCHIBROASTERS', '/imagenes/categorias/salchipapas-y-salchibroasters/banner.webp') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, name = EXCLUDED.name, image = EXCLUDED.image;
INSERT INTO public.categories (id, slug, name, image) VALUES ('C0010', 'adicional', 'ADICIONAL', 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&auto=format&fit=crop&q=80') ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, name = EXCLUDED.name, image = EXCLUDED.image;

-- B. PLATOS / PRODUCTOS DEL ADMIN Y CARTA (57) - IDs: PL0001 a PL0057
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0001', 'PROMO BUCHI DUO', 'C0001', 'promociones', 22, 'Una experiencia pensada para dos. Disfruta de dos Hamburguesas Tipo Clásica elaboradas con nuestra hamburguesa artesanal premium, acompañadas de dos Gaseosas Personales Pepsi.', TRUE, 50, '/imagenes/portada/Portada2E.webp', TRUE, '["Papa crocante","Hamburguesa artesanal","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0002', 'PROMO BROASTER FAMILIAR EDITADO', 'C0001', 'promociones', 38, 'Acompañado de papas y cremas.', TRUE, 15, '/imagenes/productos/fallback.webp', TRUE, '["Papas Fritas","Inca Kola 1.5L"]'::jsonb, '["Mostaza","Ketchup","Ají de Rocoto"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0003', 'PROMO SALCHI BURGER', 'C0001', 'promociones', 24, 'La fusión de nuestros dos clásicos más pedidos. Una Hamburguesa Tipo Cheese Burguer y una Salchipapa Tipo Salchipapa Clásica, acompañadas de una Gaseosa Personal Coca Cola.', TRUE, 50, '/imagenes/portada/Portada3E.webp', TRUE, '["Queso cheddar","Papa crocante","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara","Ají Charapita","Acevichada","Salsa BBQ","Salsa Golf","Ocopa","Aceituna","Vinagreta"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0004', 'PROMO SELVA POWER', 'C0001', 'promociones', 29, 'Un homenaje a la Amazonía. Compuesto por un Plato Amazónico Tipo Tacacho con Cecina y un Salchibroaster Tipo Salchibroaster Pierna Presa Pierna, junto a una Gaseosa Personal Fanta.', TRUE, 50, '/imagenes/portada/Portada4E.webp', TRUE, '["Maduros fritos","Sarza criolla","Papa crocante","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0005', 'Acevichadas', 'C0002', 'alitas', 29, '5 alitas jugosas bañadas en cremosa salsa acevichada con toque marino, cítrico y picante.', TRUE, 30, 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80', TRUE, '["5 alitas","Papas crocantes"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara","Ají Charapita","Acevichada","Salsa BBQ","Salsa Golf","Ocopa","Aceituna","Vinagreta"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0006', 'BBQ', 'C0002', 'alitas', 15, '5 alitas glaseadas en salsa BBQ ahumada, dulce y jugosa con un toque ahumado irresistible.', TRUE, 25, 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=600&auto=format&fit=crop&q=80', TRUE, '["5 alitas","Papas crocantes"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0007', 'Inca Kola', 'C0003', 'bebidas', 5, 'La doradita peruana bien heladita. Burbujeante, dulce y perfecta para tu broaster crujiente.', TRUE, 50, 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0008', 'Coca Cola', 'C0003', 'bebidas', 5, 'Clásica mundial, helada al punto. Refrescancia burbujeante que combina con todo.', TRUE, 50, 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0009', 'Fanta', 'C0003', 'bebidas', 3.5, 'Naranja vibrante, dulce y chispeante. Ultra refrescante para el calor de la selva.', TRUE, 40, 'https://images.unsplash.com/photo-1624517452488-04869289c4ca?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0010', 'Pepsi', 'C0003', 'bebidas', 2, 'Ligera, refrescante y burbujeante. Ideal para acompañar tus hamburguesas artesanales.', TRUE, 40, 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0011', 'Agua Cielo', 'C0003', 'bebidas', 2.5, 'Agua de mesa pura y ligera, servida helada o al tiempo.', TRUE, 40, 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0012', 'Pecho', 'C0004', 'broaster', 18, 'Presa gigante y jugosa de pechuga con cobertura ultra crocante, arroz graneado, papas crocantes y ensalada fresca.', TRUE, 25, 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80', TRUE, '["Papa crocante","Ensalada fresca","Arroz"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0013', 'Pierna', 'C0004', 'broaster', 12, 'Pierna de pollo marinada en especias secretas y frita a la perfección crujiente.', TRUE, 25, 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=600&auto=format&fit=crop&q=80', TRUE, '["Papa crocante","Ensalada fresca","Arroz"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0014', 'Encuentro', 'C0004', 'broaster', 13, 'Encuentro broaster crocante y súper jugoso con porción completa de papas doradas y arroz.', TRUE, 25, 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80', TRUE, '["Papa crocante","Ensalada fresca","Arroz"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0015', 'Ala', 'C0004', 'broaster', 10, 'Ala broaster extra crujiente servida con papas crocantes, arroz y cremas artesanales.', TRUE, 25, 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=600&auto=format&fit=crop&q=80', TRUE, '["Papa crocante","Ensalada fresca","Arroz"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0016', 'Clásica', 'C0005', 'hamburguesas', 10, 'La hamburguesa de la casa que nunca falla. Carne artesanal jugosa, pan suave, papas crocantes y ensalada fresca.', TRUE, 30, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80', TRUE, '["Hamburguesa artesanal","Papa crocante","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0017', 'Choripán', 'C0005', 'hamburguesas', 10, 'Chorizo a la parrilla chispeante con papas crocantes y cremas. Sabor callejero elevado a premium.', TRUE, 30, 'https://images.unsplash.com/photo-1627054234594-526d705c567a?w=600&auto=format&fit=crop&q=80', TRUE, '["Papas crocantes","Chorizo","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0018', 'Hawaiana Carne', 'C0005', 'hamburguesas', 14, 'Contraste dulce y salado perfecto: piña caramelizada a la plancha, queso derretido, jamón y carne jugosa.', TRUE, 25, 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80', TRUE, '["Papa crocante","Carne artesanal","Huevo","Jamón","Queso","Piña","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0019', 'Hawaiana Pollo', 'C0005', 'hamburguesas', 13, 'Pollo crispy crocante con piña asada, queso fundido, jamón y papas doradas.', TRUE, 25, 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=600&auto=format&fit=crop&q=80', TRUE, '["Papa crocante","Pollo crispy","Huevo","Jamón","Queso","Piña","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0020', 'Pollo Deshilachado', 'C0005', 'hamburguesas', 9, 'Generosa porción de pechuga deshilachada jugosa con mayonesa casera, papas crocantes y cremas.', TRUE, 25, 'https://images.unsplash.com/photo-1603064752734-4c48eff53d05?w=600&auto=format&fit=crop&q=80', TRUE, '["Papas crocantes","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0021', 'Filete de Pollo', 'C0005', 'hamburguesas', 11, 'Filete de pechuga a la plancha sazonado con hierbas, papas crujientes y ensalada fresca.', TRUE, 25, 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&auto=format&fit=crop&q=80', TRUE, '["Papas crocantes","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0022', 'Cheese Burguer', 'C0005', 'hamburguesas', 11, 'Carne artesanal bañada en doble capa de queso cheddar fundido.', TRUE, 30, 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80', TRUE, '["Queso cheddar"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0023', 'Bacon Burguer', 'C0005', 'hamburguesas', 12, 'Carne artesanal premium, tiras crocantes de tocino ahumado y queso fundido.', TRUE, 30, 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&auto=format&fit=crop&q=80', TRUE, '["Papas crocantes","Tocino","Queso"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0024', 'La Suprema', 'C0005', 'hamburguesas', 15, 'Nuestra creación más contundente: doble carne, tocino crocante, queso fundido, huevo frito y jamón.', TRUE, 25, 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80', TRUE, '["Tocino","Queso","Huevo frito","Jamón"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0025', 'Hamburguesa a lo Pobre', 'C0005', 'hamburguesas', 14, 'El sabor criollo definitivo: carne artesanal, huevo frito con yema tierna, plátano maduro frito, queso y jamón.', TRUE, 30, 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=600&auto=format&fit=crop&q=80', TRUE, '["Huevo frito","Queso","Jamón","Plátano"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0026', 'Royal', 'C0005', 'hamburguesas', 13, 'Carne casera jugosa, pollo deshilachado, huevo y jamón.', TRUE, 25, 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=600&auto=format&fit=crop&q=80', TRUE, '["Carne casera","Pollo deshilachado","Pollo","Chorizo"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0027', 'Royal a lo Pobre', 'C0005', 'hamburguesas', 14, 'La combinación maestra: carne artesanal, huevo frito, jamón, queso, plátano maduro frito, papas crocantes y ensalada fresca.', TRUE, 25, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80', TRUE, '["Papa crocante","Carne artesanal","Huevo","Jamón","Queso","Plátano","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0028', 'Anís', 'C0006', 'infusiones', 2.5, 'Infusión digestiva natural caliente con anís en grano seleccionado.', TRUE, 30, 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0029', 'Té', 'C0006', 'infusiones', 2.5, 'Té negro aromático caliente servido con rodaja de limón.', TRUE, 30, 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0030', 'Café', 'C0006', 'infusiones', 3, 'Café pasado gota a gota de grano selecto de la selva central, aromático y reconfortante.', TRUE, 35, 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0031', 'Patacones con Chorizo', 'C0007', 'platos-amazonicos', 12, 'Dorados y crujientes patacones artesanales con chorizo amazónico jugoso.', TRUE, 25, 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=600&auto=format&fit=crop&q=80', TRUE, '["Patacones","Chorizo"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0032', 'Tacacho con Cecina', 'C0007', 'platos-amazonicos', 12, 'El abrazo de la selva. Tacacho ahumado en leña con cecina premium de Tarapoto, maduros fritos y sarza criolla.', TRUE, 30, 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80', TRUE, '["Maduros fritos","Sarza criolla"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0033', 'Juanes', 'C0007', 'platos-amazonicos', 15, 'Tradición envuelta en hoja de bijao. Arroz selvático sazonado con mishkina, gallina de chacra y maduros fritos.', TRUE, 25, '/imagenes/categorias/platos-amazonicos/banner.webp', TRUE, '["Maduros fritos"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0034', 'Chilcano de Carachama o Pescado del Día', 'C0007', 'platos-amazonicos', 15, 'Caldo ancestral reconstituyente con pescado fresco de río, inguiri, plátano verde y culantro amazónico.', TRUE, 20, 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80', TRUE, '["Inguiri","Plátano"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0035', 'Palometa Frita con Maduro o Plátano', 'C0007', 'platos-amazonicos', 15, 'Pescado de río entero frito con piel extra crocante, servido con arroz blanco y maduro frito.', TRUE, 20, 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80', TRUE, '["Arroz","Maduro frito"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0036', 'Caldo Amazónico', 'C0007', 'platos-amazonicos', 12, 'Sopa reconfortante de gallina de chacra con sachaculantro, yuca suave y verduras de la selva.', TRUE, 20, 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80', TRUE, '["Yuca","Verduras de la selva"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0037', 'Arroz Chaufa Amazónico', 'C0007', 'platos-amazonicos', 15, 'Chaufa salteado al wok al fuego vivo con cecina ahumada y chorizo amazónico salteado.', TRUE, 30, 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80', TRUE, '["Cecina y chorizo amazónico salteado"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0038', 'Maracuyá', 'C0008', 'refrescos', 3, 'Zumo de pura fruta de maracuyá natural, cítrico y bien helado.', TRUE, 40, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0039', 'Chicha', 'C0008', 'refrescos', 3, 'Chicha morada casera hervida con maíz morado, manzana, piña, canela y clavo de olor.', TRUE, 40, 'https://images.unsplash.com/photo-1546173159-315724a31696?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0040', 'Cocona', 'C0008', 'refrescos', 3, 'Refresco amazónico de pura cocona de la selva, cítrico y ultra refrescante.', TRUE, 40, 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0041', 'Aguajina', 'C0008', 'refrescos', 3, 'Bebida cremosa y tradicional de pulpa fresca de aguaje amazónico helado.', TRUE, 40, 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0042', 'Camu Camu', 'C0008', 'refrescos', 3, 'Poderosa vitamina C natural en un refresco delicioso y energizante de la Amazonía.', TRUE, 40, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0043', 'Salchipapa Clásica', 'C0009', 'salchipapas', 10, 'Montaña de papas crocantes con salchichas en rodajas doradas y ensalada fresca.', TRUE, 35, 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80', TRUE, '["Papas crocantes","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0044', 'Salchipapa a lo Pobre', 'C0009', 'salchipapas', 13, 'La clásica con poder extra: huevo frito, plátano maduro dulce, papas crocantes y ensalada fresca.', TRUE, 30, 'https://images.unsplash.com/photo-1576107232684-1279f390859f?w=600&auto=format&fit=crop&q=80', TRUE, '["Papas crocantes","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0045', 'Salchibroaster Pecho', 'C0009', 'salchipapas', 20, 'Montaña de papas crocantes con pecho broaster gigante, crujiente por fuera y jugoso por dentro, más ensalada fresca.', TRUE, 25, 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80', TRUE, '["Papas crocantes","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0046', 'Salchibroaster Pierna', 'C0009', 'salchipapas', 14, 'Pierna broaster dorada sobre papas crocantes y ensalada fresca.', TRUE, 30, 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=600&auto=format&fit=crop&q=80', TRUE, '["Papas crocantes","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0047', 'Salchibroaster Encuentro', 'C0009', 'salchipapas', 16, 'Mix broaster generoso de encuentro con papas crocantes, ensalada fresca y cremas.', TRUE, 25, 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80', TRUE, '["Papas crocantes","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0048', 'Salchibroaster Ala', 'C0009', 'salchipapas', 13, 'Ala broaster crujiente sobre base de papas crocantes, con ensalada fresca y cremas.', TRUE, 25, 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=600&auto=format&fit=crop&q=80', TRUE, '["Papas crocantes","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0049', 'Salchichorizo', 'C0009', 'salchipapas', 13, 'Explosión de sabor con chorizo parrillero ahumado, papas crocantes, ensalada fresca y cremas.', TRUE, 30, 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=600&auto=format&fit=crop&q=80', TRUE, '["Papas crocantes","Ensalada fresca"]'::jsonb, '["Mayonesa","Mostaza","Ketchup","Ají de Rocoto","Tártara"]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0050', 'Huevo', 'C0010', 'adicional', 2, 'Huevo frito adicional preparado al momento con yema tierna.', TRUE, 50, 'https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0051', 'Queso', 'C0010', 'adicional', 2, 'Lámina extra de queso fundido para tus hamburguesas o platos.', TRUE, 50, 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0052', 'Piña', 'C0010', 'adicional', 2, 'Rodaja de piña dulce caramelizada a la plancha.', TRUE, 50, 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0053', 'Plátano', 'C0010', 'adicional', 2, 'Porción de plátano maduro frito caramelizado.', TRUE, 50, 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0054', 'Jamón', 'C0010', 'adicional', 2, 'Lámina de jamón especial sellado a la plancha.', TRUE, 50, 'https://images.unsplash.com/photo-1524438418049-ab2acb7aa48f?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0055', 'Tocino', 'C0010', 'adicional', 2, 'Tiras de tocino ahumado frito bien crocante.', TRUE, 50, 'https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0056', 'Pollo Broaster', 'C0010', 'adicional', 5, 'Presa extra de pollo broaster crujiente individual.', TRUE, 35, 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;
INSERT INTO public.products (id, name, category_id, category, price, description, available, stock, image, includes_sauces, accompaniments, cremas) VALUES ('PL0057', 'Hamburguesa', 'C0010', 'adicional', 5, 'Carne artesanal extra de la casa a la plancha.', TRUE, 35, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80', FALSE, '[]'::jsonb, '[]'::jsonb) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, stock = EXCLUDED.stock, available = EXCLUDED.available, image = EXCLUDED.image, accompaniments = EXCLUDED.accompaniments, cremas = EXCLUDED.cremas;

-- C. PROMOCIONES OFICIALES (4) - IDs: promo-1 a promo-4
INSERT INTO public.promotions (id, title, description, price, original_price, image, badge, active, order_num, features, accompaniments) VALUES ('promo-1', 'PROMO BUCHI DUO', 'Una experiencia pensada para dos. Disfruta de dos Hamburguesas Tipo Clásica elaboradas con nuestra hamburguesa artesanal premium, acompañadas de dos Gaseosas Personales Pepsi.', 22, 26, '/imagenes/portada/Portada2E.webp', 'DÚO FAVORITO', TRUE, 1, '["2 Hamburguesas artesanales clásicas","Papa crocante","Ensalada fresca","2 Gaseosas Personales Pepsi"]'::jsonb, '["Papa crocante","Hamburguesa artesanal","Ensalada fresca"]'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, price = EXCLUDED.price, image = EXCLUDED.image, active = EXCLUDED.active, features = EXCLUDED.features;
INSERT INTO public.promotions (id, title, description, price, original_price, image, badge, active, order_num, features, accompaniments) VALUES ('promo-2', 'PROMO BROASTER FAMILIAR', 'La selección ideal para compartir en familia. Incluye un Broaster Presa Pecho, un Broaster Presa Pierna y un Broaster Presa Ala, con el sabor crujiente que nos caracteriza, más una Gaseosa Personal Inca Kola.', 38, 46, '/imagenes/portada/Portada1E.webp', 'FAMILIAR CRUNCH', TRUE, 2, '["3 Presas Broaster (Pecho, Pierna, Ala)","Papa crocante","Ensalada fresca","Arroz graneado","1 Gaseosa Personal Inca Kola"]'::jsonb, '["Papa crocante","Ensalada fresca","Arroz"]'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, price = EXCLUDED.price, image = EXCLUDED.image, active = EXCLUDED.active, features = EXCLUDED.features;
INSERT INTO public.promotions (id, title, description, price, original_price, image, badge, active, order_num, features, accompaniments) VALUES ('promo-3', 'PROMO SALCHI BURGER', 'La fusión de nuestros dos clásicos más pedidos. Una Hamburguesa Tipo Cheese Burguer y una Salchipapa Tipo Salchipapa Clásica, acompañadas de una Gaseosa Personal Coca Cola.', 24, 29, '/imagenes/portada/Portada3E.webp', 'COMBO FUSIÓN', TRUE, 3, '["1 Hamburguesa Cheese Burguer","1 Salchipapa Clásica con Papas crocantes","Queso cheddar derretido","Ensalada fresca","1 Gaseosa Personal Coca Cola"]'::jsonb, '["Queso cheddar","Papa crocante","Ensalada fresca"]'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, price = EXCLUDED.price, image = EXCLUDED.image, active = EXCLUDED.active, features = EXCLUDED.features;
INSERT INTO public.promotions (id, title, description, price, original_price, image, badge, active, order_num, features, accompaniments) VALUES ('promo-4', 'PROMO SELVA POWER', 'Un homenaje a la Amazonía. Compuesto por un Plato Amazónico Tipo Tacacho con Cecina y un Salchibroaster Tipo Salchibroaster Pierna Presa Pierna, junto a una Gaseosa Personal Fanta.', 29, 35, '/imagenes/portada/Portada4E.webp', '100% AMAZÓNICO', TRUE, 4, '["1 Plato Amazónico Tacacho con Cecina","1 Salchibroaster Pierna","Maduros fritos","Sarza criolla","Papa crocante","Ensalada fresca","1 Gaseosa Personal Fanta"]'::jsonb, '["Maduros fritos","Sarza criolla","Papa crocante","Ensalada fresca"]'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, price = EXCLUDED.price, image = EXCLUDED.image, active = EXCLUDED.active, features = EXCLUDED.features;

-- D. PORTADAS Y BANNERS DEL HERO SLIDER (5) - IDs: portada-1 a portada-5
INSERT INTO public.portadas (id, title, highlight, subtitle, badge, badge_type, image, image_mobile, button_text, button_category, features, active, order_num) VALUES ('portada-1', 'Portada 1', NULL, NULL, NULL, NULL, '/imagenes/portada/Portada1E.webp', '/imagenes/portada/Portada1M.webp', NULL, NULL, '[]'::jsonb, TRUE, 1) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, image = EXCLUDED.image, image_mobile = EXCLUDED.image_mobile, active = EXCLUDED.active, order_num = EXCLUDED.order_num;
INSERT INTO public.portadas (id, title, highlight, subtitle, badge, badge_type, image, image_mobile, button_text, button_category, features, active, order_num) VALUES ('portada-2', 'Portada 2', NULL, NULL, NULL, NULL, '/imagenes/portada/Portada2E.webp', '/imagenes/portada/Portada2M.webp', NULL, NULL, '[]'::jsonb, TRUE, 2) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, image = EXCLUDED.image, image_mobile = EXCLUDED.image_mobile, active = EXCLUDED.active, order_num = EXCLUDED.order_num;
INSERT INTO public.portadas (id, title, highlight, subtitle, badge, badge_type, image, image_mobile, button_text, button_category, features, active, order_num) VALUES ('portada-3', 'Portada 3', NULL, NULL, NULL, NULL, '/imagenes/portada/Portada3E.webp', '/imagenes/portada/Portada3M.webp', NULL, NULL, '[]'::jsonb, TRUE, 3) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, image = EXCLUDED.image, image_mobile = EXCLUDED.image_mobile, active = EXCLUDED.active, order_num = EXCLUDED.order_num;
INSERT INTO public.portadas (id, title, highlight, subtitle, badge, badge_type, image, image_mobile, button_text, button_category, features, active, order_num) VALUES ('portada-4', 'Portada 4', NULL, NULL, NULL, NULL, '/imagenes/portada/Portada4E.webp', '/imagenes/portada/Portada4M.webp', NULL, NULL, '[]'::jsonb, TRUE, 4) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, image = EXCLUDED.image, image_mobile = EXCLUDED.image_mobile, active = EXCLUDED.active, order_num = EXCLUDED.order_num;
INSERT INTO public.portadas (id, title, highlight, subtitle, badge, badge_type, image, image_mobile, button_text, button_category, features, active, order_num) VALUES ('portada-1790590297016', 'Portada 5', NULL, 'Promoción especial BuchiSapa Burger & Broaster', 'DESTACADO', 'red-pill', '/imagenes/portada/Portada5E.webp', '/imagenes/portada/Portada5M.webp', 'VER CARTA', 'todos', '["SABOR AMAZÓNICO","PREPARADO AL MOMENTO"]'::jsonb, TRUE, 5) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, image = EXCLUDED.image, image_mobile = EXCLUDED.image_mobile, active = EXCLUDED.active, order_num = EXCLUDED.order_num;

-- E. CLIENTES Y ADMINISTRADORES REALES DEL PANEL ADMIN (perfiles)
INSERT INTO public.perfiles (id, uid, email, name, first_name, last_name, phone, doc_type, doc_number, role, is_admin, email_verified) VALUES ('9b1fabb3-25d9-4c0a-921a-8d5a460e8a91', '9b1fabb3-25d9-4c0a-921a-8d5a460e8a91', 'admin@buchisapa.pe', 'Administrador Buchisapa', 'Admin', 'Buchisapa', '943 312 024', 'DNI', '72345678', 'admin', TRUE, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, phone = EXCLUDED.phone, doc_number = EXCLUDED.doc_number;
INSERT INTO public.perfiles (id, uid, email, name, first_name, last_name, phone, doc_type, doc_number, role, is_admin, email_verified) VALUES ('166099db-28ad-4329-b3c4-117f63188472', '166099db-28ad-4329-b3c4-117f63188472', 'buchisapaweb@gmail.com', 'Administrador BuchiSapa', 'Administrador', 'BuchiSapa', '942 475 459', 'DNI', '70000001', 'admin', TRUE, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, phone = EXCLUDED.phone, doc_number = EXCLUDED.doc_number;
INSERT INTO public.perfiles (id, uid, email, name, first_name, last_name, phone, doc_type, doc_number, role, is_admin, email_verified) VALUES ('loalopezjean', 'loalopezjean', 'loalopezjean@gmail.com', 'Jean Loa Lopez', 'Jean', 'Loa Lopez', '942 475 459', 'DNI', '74859612', 'admin', TRUE, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, phone = EXCLUDED.phone, doc_number = EXCLUDED.doc_number;
INSERT INTO public.perfiles (id, uid, email, name, first_name, last_name, phone, doc_type, doc_number, role, is_admin, email_verified) VALUES ('cust-buchisapa-1', 'cust-buchisapa-1', 'cliente@buchisapa.pe', 'Cliente Buchisapa', 'Cliente', 'Buchisapa', '987 654 321', 'DNI', '45678901', 'customer', FALSE, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, phone = EXCLUDED.phone, doc_number = EXCLUDED.doc_number;
INSERT INTO public.perfiles (id, uid, email, name, first_name, last_name, phone, doc_type, doc_number, role, is_admin, email_verified) VALUES ('1', '1', 'juan.perez@gmail.com', 'Juan Perez', 'Juan', 'Perez', '987654321', 'DNI', '45678902', 'customer', FALSE, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, phone = EXCLUDED.phone, doc_number = EXCLUDED.doc_number;
INSERT INTO public.perfiles (id, uid, email, name, first_name, last_name, phone, doc_type, doc_number, role, is_admin, email_verified) VALUES ('2', '2', 'maria.garcia@gmail.com', 'Maria Garcia', 'Maria', 'Garcia', '912345678', 'DNI', '45678903', 'customer', FALSE, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, phone = EXCLUDED.phone, doc_number = EXCLUDED.doc_number;
INSERT INTO public.perfiles (id, uid, email, name, first_name, last_name, phone, doc_type, doc_number, role, is_admin, email_verified) VALUES ('3', '3', 'carlos.lopez@gmail.com', 'Carlos Lopez', 'Carlos', 'Lopez', '955443322', 'DNI', '45678904', 'customer', FALSE, TRUE) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, phone = EXCLUDED.phone, doc_number = EXCLUDED.doc_number;

-- F. CONFIGURACION DEL NEGOCIO E IMPRESORA TERMICA
INSERT INTO public.configuracion (id, business_name, ruc, address, phone, email, delivery_fee, printer_ip, printer_port, opening_hours) VALUES ('principal', 'BuchiSapa Burger & Broaster', '10723456781', 'Jr. San Martin 456, Tarapoto, San Martin, Peru', '+51 942 475 459', 'buchisapaweb@gmail.com', 3.00, '192.168.8.100', 80, 'Lunes a Domingo: 5:00 PM - 11:30 PM') ON CONFLICT (id) DO UPDATE SET business_name = EXCLUDED.business_name, ruc = EXCLUDED.ruc, address = EXCLUDED.address, phone = EXCLUDED.phone, email = EXCLUDED.email, printer_ip = EXCLUDED.printer_ip;
