#!/usr/bin/env bash
# Script para crear la estructura completa de BUCHISAPA (archivos vacíos / sin código)

mkdir -p \
  "interfaz/src/componentes" \
  "interfaz/src/paginas" \
  "interfaz/src/estilos" \
  "interfaz/src/javascript" \
  "interfaz/src/administracion/componentes" \
  "interfaz/src/administracion/paginas" \
  "interfaz/src/administracion/rutas" \
  "interfaz/src/administracion/estilos" \
  "interfaz/src/recursos/imagenes/administracion" \
  "interfaz/src/recursos/imagenes/logo" \
  "interfaz/src/recursos/imagenes/portada" \
  "interfaz/src/recursos/imagenes/categorias/adicionales/productos" \
  "interfaz/src/recursos/imagenes/categorias/alitas/productos" \
  "interfaz/src/recursos/imagenes/categorias/bebidas/productos" \
  "interfaz/src/recursos/imagenes/categorias/broaster/productos" \
  "interfaz/src/recursos/imagenes/categorias/hamburguesas/productos" \
  "interfaz/src/recursos/imagenes/categorias/infusiones/productos" \
  "interfaz/src/recursos/imagenes/categorias/platos-amazonicos/productos" \
  "interfaz/src/recursos/imagenes/categorias/promociones/productos" \
  "interfaz/src/recursos/imagenes/categorias/refrescos/productos" \
  "interfaz/src/recursos/imagenes/categorias/salchipapas-y-salchibroasters/productos" \
  "datos" \
  "servidor/src/base-datos" \
  "servidor/src/intermediarios" \
  "servidor/src/servicios" \
  "servidor/src/utilidades/supabase" \
  "api" \
  "publico" \
  "supabase/migraciones" \
  "scripts"

touch \
  "interfaz/LEEME.md" \
  "interfaz/src/componentes/carrusel-portada.html" \
  "interfaz/src/componentes/categoria.html" \
  "interfaz/src/componentes/encabezado.html" \
  "interfaz/src/componentes/inicio-sesion.html" \
  "interfaz/src/componentes/pie-pagina.html" \
  "interfaz/src/paginas/carrito.html" \
  "interfaz/src/paginas/contacto.html" \
  "interfaz/src/paginas/historia.html" \
  "interfaz/src/paginas/informacion.html" \
  "interfaz/src/paginas/nosotros.html" \
  "interfaz/src/paginas/pago.html" \
  "interfaz/src/paginas/politicas.html" \
  "interfaz/src/paginas/privacidad.html" \
  "interfaz/src/paginas/producto-detalle.html" \
  "interfaz/src/paginas/reclamaciones.html" \
  "interfaz/src/paginas/servicios.html" \
  "interfaz/src/paginas/terminos.html" \
  "interfaz/src/paginas/ubicacion.html" \
  "interfaz/src/paginas/valores.html" \
  "interfaz/src/paginas/valores-nutricionales.html" \
  "interfaz/src/paginas/vision.html" \
  "interfaz/src/estilos/variables.css" \
  "interfaz/src/estilos/responsivo.css" \
  "interfaz/src/estilos/carrusel-portada.css" \
  "interfaz/src/estilos/categoria.css" \
  "interfaz/src/estilos/encabezado.css" \
  "interfaz/src/estilos/inicio-sesion.css" \
  "interfaz/src/estilos/pie-pagina.css" \
  "interfaz/src/estilos/carrito.css" \
  "interfaz/src/estilos/contacto.css" \
  "interfaz/src/estilos/historia.css" \
  "interfaz/src/estilos/informacion.css" \
  "interfaz/src/estilos/nosotros.css" \
  "interfaz/src/estilos/pago.css" \
  "interfaz/src/estilos/politicas.css" \
  "interfaz/src/estilos/privacidad.css" \
  "interfaz/src/estilos/producto-detalle.css" \
  "interfaz/src/estilos/reclamaciones.css" \
  "interfaz/src/estilos/servicios.css" \
  "interfaz/src/estilos/terminos.css" \
  "interfaz/src/estilos/ubicacion.css" \
  "interfaz/src/estilos/valores.css" \
  "interfaz/src/estilos/valores-nutricionales.css" \
  "interfaz/src/estilos/vision.css" \
  "interfaz/src/javascript/inicio.js" \
  "interfaz/src/javascript/encabezado.js" \
  "interfaz/src/javascript/inicio-sesion.js" \
  "interfaz/src/javascript/categorias.js" \
  "interfaz/src/javascript/carrusel-portada.js" \
  "interfaz/src/javascript/categoria.js" \
  "interfaz/src/javascript/carrito.js" \
  "interfaz/src/javascript/contacto.js" \
  "interfaz/src/javascript/informacion.js" \
  "interfaz/src/javascript/nosotros.js" \
  "interfaz/src/javascript/pago.js" \
  "interfaz/src/javascript/politicas.js" \
  "interfaz/src/javascript/privacidad.js" \
  "interfaz/src/javascript/producto-detalle.js" \
  "interfaz/src/javascript/reclamaciones.js" \
  "interfaz/src/javascript/servicios.js" \
  "interfaz/src/javascript/terminos.js" \
  "interfaz/src/javascript/ubicacion.js" \
  "interfaz/src/javascript/valores.js" \
  "interfaz/src/javascript/valores-nutricionales.js" \
  "interfaz/src/javascript/vision.js" \
  "interfaz/src/javascript/cliente-supabase.js" \
  "interfaz/src/javascript/horario.js" \
  "interfaz/src/javascript/impresora.js" \
  "interfaz/src/javascript/personalizador.js" \
  "interfaz/src/javascript/ubigeo-peru.js" \
  "interfaz/src/administracion/admin.html" \
  "interfaz/src/administracion/componentes/encabezado.html" \
  "interfaz/src/administracion/paginas/categorias.html" \
  "interfaz/src/administracion/paginas/clientes.html" \
  "interfaz/src/administracion/paginas/comprobante.html" \
  "interfaz/src/administracion/paginas/configuracion.html" \
  "interfaz/src/administracion/paginas/insumos.html" \
  "interfaz/src/administracion/paginas/panel.html" \
  "interfaz/src/administracion/paginas/pedidos.html" \
  "interfaz/src/administracion/paginas/portada.html" \
  "interfaz/src/administracion/paginas/productos.html" \
  "interfaz/src/administracion/paginas/utensilios.html" \
  "interfaz/src/administracion/rutas/administracion.js" \
  "interfaz/src/administracion/rutas/categorias.js" \
  "interfaz/src/administracion/rutas/clientes.js" \
  "interfaz/src/administracion/rutas/comprobante.js" \
  "interfaz/src/administracion/rutas/configuracion.js" \
  "interfaz/src/administracion/rutas/encabezado.js" \
  "interfaz/src/administracion/rutas/insumos.js" \
  "interfaz/src/administracion/rutas/panel.js" \
  "interfaz/src/administracion/rutas/pedidos.js" \
  "interfaz/src/administracion/rutas/portada.js" \
  "interfaz/src/administracion/rutas/productos.js" \
  "interfaz/src/administracion/rutas/utensilios.js" \
  "interfaz/src/administracion/estilos/categorias.css" \
  "interfaz/src/administracion/estilos/clientes.css" \
  "interfaz/src/administracion/estilos/comprobante.css" \
  "interfaz/src/administracion/estilos/configuracion.css" \
  "interfaz/src/administracion/estilos/encabezado.css" \
  "interfaz/src/administracion/estilos/insumos.css" \
  "interfaz/src/administracion/estilos/panel.css" \
  "interfaz/src/administracion/estilos/pedidos.css" \
  "interfaz/src/administracion/estilos/portada.css" \
  "interfaz/src/administracion/estilos/productos.css" \
  "interfaz/src/administracion/estilos/utensilios.css" \
  "interfaz/src/recursos/imagenes/portada/Portada1E.webp" \
  "interfaz/src/recursos/imagenes/portada/Portada1M.webp" \
  "interfaz/src/recursos/imagenes/portada/Portada2E.webp" \
  "interfaz/src/recursos/imagenes/portada/Portada2M.webp" \
  "interfaz/src/recursos/imagenes/portada/Portada3E.webp" \
  "interfaz/src/recursos/imagenes/portada/Portada3M.webp" \
  "interfaz/src/recursos/imagenes/portada/Portada4E.webp" \
  "interfaz/src/recursos/imagenes/portada/Portada4M.webp" \
  "interfaz/src/recursos/imagenes/categorias/adicionales/banner.webp" \
  "interfaz/src/recursos/imagenes/categorias/alitas/banner.webp" \
  "interfaz/src/recursos/imagenes/categorias/bebidas/banner.webp" \
  "interfaz/src/recursos/imagenes/categorias/broaster/banner.webp" \
  "interfaz/src/recursos/imagenes/categorias/hamburguesas/banner.webp" \
  "interfaz/src/recursos/imagenes/categorias/infusiones/banner.webp" \
  "interfaz/src/recursos/imagenes/categorias/platos-amazonicos/banner.webp" \
  "interfaz/src/recursos/imagenes/categorias/promociones/banner.webp" \
  "interfaz/src/recursos/imagenes/categorias/refrescos/banner.webp" \
  "interfaz/src/recursos/imagenes/categorias/salchipapas-y-salchibroasters/banner.webp" \
  "datos/categorias.json" \
  "datos/productos.json" \
  "datos/acompanamientos.json" \
  "datos/cremas.json" \
  "servidor/src/base-datos/consultas.ts" \
  "servidor/src/base-datos/usuarios.ts" \
  "servidor/src/intermediarios/autenticacion.ts" \
  "servidor/src/servicios/verificacion-correo.ts" \
  "servidor/src/utilidades/supabase/cliente.ts" \
  "servidor/src/utilidades/supabase/intermediario.ts" \
  "servidor/src/utilidades/supabase/servidor.ts" \
  "api/index.ts" \
  "publico/manifiesto.json" \
  "publico/trabajador-servicio.js" \
  "supabase/config.toml" \
  "scripts/compilar-html.js" \
  "index.html" \
  "servidor.ts" \
  "package.json" \
  "tsconfig.json" \
  "tsconfig.node.json" \
  "vite.config.ts" \
  "vercel.json" \
  "Dockerfile" \
  ".env.example" \
  ".gitignore" \
  ".dockerignore" \
  "LEEME.md" \
  "ESTRUCTURA-ADMIN.md" \
  "ESTRUCTURA-COMPLETA.txt" \
  "VERIFICACION-INICIO-SESION-ADMIN.md"

echo "Estructura creada con éxito sin código."
