import fs from 'fs';
import path from 'path';

const filePath = path.join(process.cwd(), 'backend/src/db/queries.ts');
let content = fs.readFileSync(filePath, 'utf8');

// List of all products provided by the user with their standard properties and correct image URLs
const products = [
  // 1. ADICIONALES (C0001)
  {
    id: "PL00001",
    code: "PL00001",
    name: "Hamburguesa",
    category: "ADICIONALES",
    category_id: "C0001",
    price: 5,
    description: "Porción adicional de hamburguesa artesanal, perfecta para complementar tus preparaciones y disfrutar un extra de sabor casero.",
    badge: "EXTRA",
    popular: false,
    available: true,
    stock: 50,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00002",
    code: "PL00002",
    name: "Huevo",
    category: "ADICIONALES",
    category_id: "C0001",
    price: 2,
    description: "Huevo preparado al momento, ideal para complementar tus platos favoritos y agregar un toque extra de sabor a cada preparación.",
    badge: "EXTRA",
    popular: false,
    available: true,
    stock: 100,
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00003",
    code: "PL00003",
    name: "Jamón",
    category: "ADICIONALES",
    category_id: "C0001",
    price: 2,
    description: "Porción adicional de jamón, ideal para complementar hamburguesas y preparaciones especiales con un sabor suave y agradable.",
    badge: "EXTRA",
    popular: false,
    available: true,
    stock: 80,
    image: "https://images.unsplash.com/photo-1524438418049-ab2acb7aa48f?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00004",
    code: "PL00004",
    name: "Piña",
    category: "ADICIONALES",
    category_id: "C0001",
    price: 2,
    description: "Porción adicional de piña, ideal para complementar preparaciones y aportar un toque fresco, dulce y agradable a cada plato.",
    badge: "EXTRA",
    popular: false,
    available: true,
    stock: 80,
    image: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00005",
    code: "PL00005",
    name: "Plátano",
    category: "ADICIONALES",
    category_id: "C0001",
    price: 2,
    description: "Porción adicional de plátano, perfecta para complementar diferentes preparaciones y disfrutar un sabor tradicional en cada bocado.",
    badge: "EXTRA",
    popular: false,
    available: true,
    stock: 80,
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00006",
    code: "PL00006",
    name: "Pollo Broaster",
    category: "ADICIONALES",
    category_id: "C0001",
    price: 5,
    description: "Porción adicional de pollo broaster dorado y crujiente, ideal para complementar tus platos y disfrutar un extra de sabor.",
    badge: "EXTRA",
    popular: false,
    available: true,
    stock: 50,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00007",
    code: "PL00007",
    name: "Queso",
    category: "ADICIONALES",
    category_id: "C0001",
    price: 2,
    description: "Porción adicional de queso, perfecta para complementar hamburguesas y otras preparaciones con una textura cremosa y sabrosa.",
    badge: "EXTRA",
    popular: false,
    available: true,
    stock: 80,
    image: "https://images.unsplash.com/photo-1552767059-ce182ead8c1b?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00008",
    code: "PL00008",
    name: "Tocino",
    category: "ADICIONALES",
    category_id: "C0001",
    price: 2,
    description: "Porción adicional de tocino, perfecta para aportar un toque crocante y un sabor intenso a tus hamburguesas y preparaciones.",
    badge: "EXTRA",
    popular: false,
    available: true,
    stock: 80,
    image: "https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },

  // 2. ALITAS (C0002)
  {
    id: "PL00009",
    code: "PL00009",
    name: "Acevichadas",
    category: "ALITAS",
    category_id: "C0002",
    price: 15,
    description: "Cinco alitas preparadas con un toque acevichado, combinando sabores frescos e intensos en una propuesta llena de sabor.",
    badge: "ACEVICHADAS",
    popular: true,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00010",
    code: "PL00010",
    name: "BBQ",
    category: "ALITAS",
    category_id: "C0002",
    price: 15,
    description: "Cinco alitas bañadas en salsa BBQ, con un sabor ahumado y ligeramente dulce que combina perfectamente con su textura crocante.",
    badge: "BBQ",
    popular: true,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1527477378308-140ae2443325?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },

  // 3. BEBIDAS (C0003)
  {
    id: "PL00011",
    code: "PL00011",
    name: "Agua Cielo",
    category: "BEBIDAS",
    category_id: "C0003",
    price: 2.50,
    description: "Agua embotellada refrescante y ligera, ideal para acompañar tus comidas y mantener una opción sencilla durante el día.",
    badge: "NATURAL",
    popular: false,
    available: true,
    stock: 50,
    image: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00012",
    code: "PL00012",
    name: "Coca Cola",
    category: "BEBIDAS",
    category_id: "C0003",
    price: 5,
    description: "Gaseosa clásica de sabor intenso y refrescante, ideal para complementar tus comidas y disfrutar en cualquier momento.",
    badge: "PERSONAL",
    popular: true,
    available: true,
    stock: 45,
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00013",
    code: "PL00013",
    name: "Fanta",
    category: "BEBIDAS",
    category_id: "C0003",
    price: 3.50,
    description: "Gaseosa de sabor frutal y refrescante, perfecta para acompañar tus comidas y disfrutar una bebida agradable y fría.",
    badge: "PERSONAL",
    popular: false,
    available: true,
    stock: 35,
    image: "https://images.unsplash.com/photo-1624517452488-04869289c4ca?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00014",
    code: "PL00014",
    name: "Inca Kola",
    category: "BEBIDAS",
    category_id: "C0003",
    price: 5,
    description: "Gaseosa peruana de sabor dulce y refrescante, perfecta para acompañar tus platos favoritos y disfrutar bien fría.",
    badge: "POPULAR",
    popular: true,
    available: true,
    stock: 50,
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00015",
    code: "PL00015",
    name: "Pepsi",
    category: "BEBIDAS",
    category_id: "C0003",
    price: 2,
    description: "Gaseosa de sabor intenso y refrescante, ideal para acompañar diferentes platos y disfrutar durante cualquier ocasión.",
    badge: "PERSONAL",
    popular: false,
    available: true,
    stock: 40,
    image: "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },

  // 4. BROASTER (C0004)
  {
    id: "PL00016",
    code: "PL00016",
    name: "Ala",
    category: "BROASTER",
    category_id: "C0004",
    price: 10,
    description: "Ala de pollo broaster dorada y crujiente, preparada para ofrecer un bocado sabroso y lleno de textura.",
    badge: "ECONÓMICO",
    popular: false,
    available: true,
    stock: 30,
    image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00017",
    code: "PL00017",
    name: "Encuentro",
    category: "BROASTER",
    category_id: "C0004",
    price: 13,
    description: "Encuentro de pollo broaster dorado y crujiente, con una textura jugosa y un sabor especial en cada bocado.",
    badge: "BROASTER",
    popular: true,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00018",
    code: "PL00018",
    name: "Pecho",
    category: "BROASTER",
    category_id: "C0004",
    price: 18,
    description: "Pecho de pollo broaster dorado and crujiente, preparado para disfrutar una presa jugosa con el sabor característico de la casa.",
    badge: "PREMIUM",
    popular: true,
    available: true,
    stock: 30,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00019",
    code: "PL00019",
    name: "Pierna",
    category: "BROASTER",
    category_id: "C0004",
    price: 12,
    description: "Pierna de pollo broaster jugosa y crocante, preparada con un sabor casero ideal para disfrutar en cualquier ocasión.",
    badge: "CLÁSICO",
    popular: true,
    available: true,
    stock: 30,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },

  // 5. HAMBURGUESAS (C0005)
  {
    id: "PL00020",
    code: "PL00020",
    name: "Bacon Burguer",
    category: "HAMBURGUESAS",
    category_id: "C0005",
    price: 12,
    description: "Hamburguesa con tocino y queso, combinando una textura crocante con un sabor intenso para una experiencia irresistible.",
    badge: "TOCINO",
    popular: true,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00021",
    code: "PL00021",
    name: "Cheese Burguer",
    category: "HAMBURGUESAS",
    category_id: "C0005",
    price: 11,
    description: "Hamburguesa de carne acompañada de queso cheddar, creando una combinación cremosa, sabrosa y perfecta para los amantes del queso.",
    badge: "CHEDDAR",
    popular: true,
    available: true,
    stock: 30,
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00022",
    code: "PL00022",
    name: "Choripán",
    category: "HAMBURGUESAS",
    category_id: "C0005",
    price: 10,
    description: "Chorizo dorado y jugoso servido en una preparación tradicional, ideal para disfrutar un sabor intenso y casero.",
    badge: "PARRILLERO",
    popular: false,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00023",
    code: "PL00023",
    name: "Clásica",
    category: "HAMBURGUESAS",
    category_id: "C0005",
    price: 10,
    description: "Hamburguesa artesanal de sabor casero, preparada para disfrutar una combinación sencilla, sabrosa y contundente.",
    badge: "CLÁSICA",
    popular: true,
    available: true,
    stock: 35,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00024",
    code: "PL00024",
    name: "Hamburguesa a lo Pobre",
    category: "HAMBURGUESAS",
    category_id: "C0005",
    price: 14,
    description: "Una combinación de sabores caseros con ingredientes tradicionales, perfecta para disfrutar una hamburguesa abundante y especial.",
    badge: "A LO POBRE",
    popular: true,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00025",
    code: "PL00025",
    name: "Hawaiana Carne",
    category: "HAMBURGUESAS",
    category_id: "C0005",
    price: 14,
    description: "Carne artesanal combinada con sabores dulces y salados, creando una hamburguesa especial, abundante y llena de sabor.",
    badge: "HAWAIANA",
    popular: true,
    available: true,
    stock: 20,
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00026",
    code: "PL00026",
    name: "Hawaiana Pollo",
    category: "HAMBURGUESAS",
    category_id: "C0005",
    price: 13,
    description: "Pollo crispy combinado con ingredientes dulces y salados, logrando una hamburguesa especial, cremosa y muy sabrosa.",
    badge: "CRISPY",
    popular: true,
    available: true,
    stock: 20,
    image: "https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00027",
    code: "PL00027",
    name: "La Suprema",
    category: "HAMBURGUESAS",
    category_id: "C0005",
    price: 15,
    description: "Hamburguesa especial con una combinación abundante de ingredientes, ideal para quienes buscan un sabor intenso y contundente.",
    badge: "SUPREMA",
    popular: true,
    available: true,
    stock: 20,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00028",
    code: "PL00028",
    name: "Filete de Pollo",
    category: "HAMBURGUESAS",
    category_id: "C0005",
    price: 11,
    description: "Filete de pollo preparado al momento, con una textura suave y sabor casero, ideal para una comida completa.",
    badge: "CASERO",
    popular: false,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1525164286253-04e68b9d94c6?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00029",
    code: "PL00029",
    name: "Pollo Deshilachado",
    category: "HAMBURGUESAS",
    category_id: "C0005",
    price: 9,
    description: "Pollo deshilachado preparado con un toque casero, ofreciendo una opción práctica, suave y llena de sabor.",
    badge: "DESHILACHADO",
    popular: false,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1525164286253-04e68b9d94c6?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00030",
    code: "PL00030",
    name: "Royal",
    category: "HAMBURGUESAS",
    category_id: "C0005",
    price: 13,
    description: "Hamburguesa especial con una combinación generosa de carnes y embutidos, preparada para quienes buscan una opción completa y sabrosa.",
    badge: "ROYAL",
    popular: true,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00031",
    code: "PL00031",
    name: "Royal a lo Pobre",
    category: "HAMBURGUESAS",
    category_id: "C0005",
    price: 14,
    description: "Hamburguesa abundante que combina sabores caseros y tradicionales, ofreciendo una experiencia completa en cada bocado.",
    badge: "ESPECIAL",
    popular: true,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },

  // 6. INFUSIONES (C0006)
  {
    id: "PL00032",
    code: "PL00032",
    name: "Anís",
    category: "INFUSIONES",
    category_id: "C0006",
    price: 2.50,
    description: "Infusión de anís con aroma agradable y sabor suave, ideal para disfrutar caliente después de una comida o durante un descanso.",
    badge: "CALIENTE",
    popular: false,
    available: true,
    stock: 50,
    image: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00033",
    code: "PL00033",
    name: "Café",
    category: "INFUSIONES",
    category_id: "C0006",
    price: 3,
    description: "Café de aroma agradable y sabor intenso, ideal para comenzar el día o disfrutar de un momento de descanso.",
    badge: "PASADO",
    popular: true,
    available: true,
    stock: 50,
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00034",
    code: "PL00034",
    name: "Té",
    category: "INFUSIONES",
    category_id: "C0006",
    price: 2.50,
    description: "Infusión de té con sabor suave y agradable, perfecta para disfrutar caliente en cualquier momento del día.",
    badge: "CALIENTE",
    popular: false,
    available: true,
    stock: 50,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },

  // 7. PLATOS AMAZÓNICOS (C0007)
  {
    id: "PL00035",
    code: "PL00035",
    name: "Arroz Chaufa Amazónico",
    category: "PLATOS AMAZÓNICOS",
    category_id: "C0007",
    price: 15,
    description: "Arroz chaufa preparado con sabores amazónicos, combinando ingredientes tradicionales para lograr una propuesta intensa y llena de sabor.",
    badge: "FUSIÓN",
    popular: true,
    available: true,
    stock: 20,
    image: "/imagenes/categorias/platos-amazonicos/banner.webp",
    includes_sauces: true
  },
  {
    id: "PL00036",
    code: "PL00036",
    name: "Caldo Amazónico",
    category: "PLATOS AMAZÓNICOS",
    category_id: "C0007",
    price: 12,
    description: "Caldo de inspiración amazónica preparado con sabores tradicionales, ideal para disfrutar una opción caliente, reconfortante y sustanciosa.",
    badge: "TRADICIONAL",
    popular: false,
    available: true,
    stock: 15,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00037",
    code: "PL00037",
    name: "Chilcano de Carachama o Pescado del Día",
    category: "PLATOS AMAZÓNICOS",
    category_id: "C0007",
    price: 15,
    description: "Caldo amazónico preparado con carachama o pescado del día, ofreciendo un sabor tradicional, reconfortante y lleno de identidad.",
    badge: "RECONSTITUYENTE",
    popular: false,
    available: true,
    stock: 15,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00038",
    code: "PL00038",
    name: "Juanes",
    category: "PLATOS AMAZÓNICOS",
    category_id: "C0007",
    price: 15,
    description: "Preparación tradicional de la Amazonía con el sabor característico de un auténtico juane, ideal para disfrutar una receta llena de tradición.",
    badge: "TRADICIÓN",
    popular: true,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00039",
    code: "PL00039",
    name: "Palometa Frita con Maduro o Plátano",
    category: "PLATOS AMAZÓNICOS",
    category_id: "C0007",
    price: 15,
    description: "Palometa frita hasta lograr una textura dorada y crocante, combinada con guarniciones tradicionales de sabor amazónico.",
    badge: "RÍO",
    popular: false,
    available: true,
    stock: 15,
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00040",
    code: "PL00040",
    name: "Patacones con Chorizo",
    category: "PLATOS AMAZÓNICOS",
    category_id: "C0007",
    price: 12,
    description: "Crujientes patacones acompañados de chorizo dorado, ofreciendo una combinación tradicional, sabrosa y representativa de la región.",
    badge: "ENTRADA",
    popular: true,
    available: true,
    stock: 30,
    image: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00041",
    code: "PL00041",
    name: "Tacacho con Cecina",
    category: "PLATOS AMAZÓNICOS",
    category_id: "C0007",
    price: 12,
    description: "Tradicional preparación amazónica con tacacho y cecina, acompañada de sabores frescos para una experiencia llena de tradición.",
    badge: "ESTRELLA",
    popular: true,
    available: true,
    stock: 35,
    image: "/imagenes/categorias/platos-amazonicos/banner.webp",
    includes_sauces: true
  },

  // 8. PROMOCIONES (C0008) (Also included in products for client queries)
  {
    id: "PL00042",
    code: "PL00042",
    name: "PROMO BROASTER FAMILIAR",
    category: "PROMOCIONES",
    category_id: "C0008",
    price: 38,
    description: "La selección ideal para compartir en familia. Incluye un Broaster Presa Pecho, un Broaster Presa Pierna y un Broaster Presa Ala, con el sabor crujiente que nos caracteriza, más una Gaseosa Personal Inca Kola.",
    badge: "FAMILIAR",
    popular: true,
    available: true,
    stock: 50,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00043",
    code: "PL00043",
    name: "PROMO BUCHI DUO",
    category: "PROMOCIONES",
    category_id: "C0008",
    price: 22,
    description: "Una experiencia pensada para dos. Disfruta de dos Hamburguesas Tipo Clásica elaboradas con nuestra hamburguesa artesanal premium, acompañadas de dos Gaseosas Personales Pepsi.",
    badge: "DUO",
    popular: true,
    available: true,
    stock: 50,
    image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00044",
    code: "PL00044",
    name: "PROMO SALCHI BURGER",
    category: "PROMOCIONES",
    category_id: "C0008",
    price: 24,
    description: "La fusión de nuestros dos clásicos más pedidos. Una Hamburguesa Tipo Cheese Burguer y una Salchipapa Tipo Salchipapa Clásica, acompañadas de una Gaseosa Personal Coca Cola.",
    badge: "COMBO",
    popular: true,
    available: true,
    stock: 50,
    image: "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00045",
    code: "PL00045",
    name: "PROMO SELVA POWER",
    category: "PROMOCIONES",
    category_id: "C0008",
    price: 29,
    description: "Un homenaje a la Amazonía. Compuesto por un Plato Amazónico Tipo Tacacho con Cecina y un Salchibroaster Tipo Salchibroaster Pierna Presa Pierna, junto a una Gaseosa Personal Fanta.",
    badge: "SELVA",
    popular: true,
    available: true,
    stock: 50,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },

  // 9. REFRESCOS (C0009)
  {
    id: "PL00046",
    code: "PL00046",
    name: "Aguajina",
    category: "REFRESCOS",
    category_id: "C0009",
    price: 3,
    description: "Refresco de aguaje con sabor tropical y agradable, preparado para disfrutar frío y acompañar diferentes platos.",
    badge: "SELVÁTICO",
    popular: true,
    available: true,
    stock: 40,
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00047",
    code: "PL00047",
    name: "Camu Camu",
    category: "REFRESCOS",
    category_id: "C0009",
    price: 3,
    description: "Refresco de camu camu con sabor frutal y ligeramente ácido, perfecto para disfrutar frío durante cualquier ocasión.",
    badge: "VITAMINA C",
    popular: true,
    available: true,
    stock: 40,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00048",
    code: "PL00048",
    name: "Chicha",
    category: "REFRESCOS",
    category_id: "C0009",
    price: 3,
    description: "Tradicional refresco de maíz morado con sabor dulce y refrescante, perfecto para acompañar los platos de nuestra carta.",
    badge: "CASERA",
    popular: true,
    available: true,
    stock: 50,
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00049",
    code: "PL00049",
    name: "Cocona",
    category: "REFRESCOS",
    category_id: "C0009",
    price: 3,
    description: "Refresco de cocona con sabor tropical y ligeramente ácido, ideal para disfrutar frío junto a una comida especial.",
    badge: "TÍPICO",
    popular: true,
    available: true,
    stock: 40,
    image: "https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },
  {
    id: "PL00050",
    code: "PL00050",
    name: "Maracuyá",
    category: "REFRESCOS",
    category_id: "C0009",
    price: 3,
    description: "Refresco de maracuyá con sabor frutal y refrescante, ideal para disfrutar frío y acompañar tus comidas favoritas.",
    badge: "REFRESCANTE",
    popular: true,
    available: true,
    stock: 45,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80",
    includes_sauces: false
  },

  // 10. SALCHIPAPAS Y SALCHIBROASTERS (C0010)
  {
    id: "PL00051",
    code: "PL00051",
    name: "Salchibroaster Ala",
    category: "SALCHIPAPAS Y SALCHIBROASTERS",
    category_id: "C0010",
    price: 13,
    description: "Ala de pollo broaster acompañada de salchicha dorada, creando una combinación crujiente y sabrosa para disfrutar.",
    badge: "BROASTER",
    popular: false,
    available: true,
    stock: 30,
    image: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00052",
    code: "PL00052",
    name: "Salchibroaster Encuentro",
    category: "SALCHIPAPAS Y SALCHIBROASTERS",
    category_id: "C0010",
    price: 16,
    description: "Encuentro de pollo broaster combinado con salchicha, preparado para disfrutar una mezcla de sabores y texturas irresistibles.",
    badge: "ENCUENTRO",
    popular: true,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00053",
    code: "PL00053",
    name: "Salchibroaster Pecho",
    category: "SALCHIPAPAS Y SALCHIBROASTERS",
    category_id: "C0010",
    price: 20,
    description: "Pecho de pollo broaster combinado con salchicha dorada, creando una preparación abundante y llena de sabor.",
    badge: "PECHO",
    popular: true,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00054",
    code: "PL00054",
    name: "Salchibroaster Pierna",
    category: "SALCHIPAPAS Y SALCHIBROASTERS",
    category_id: "C0010",
    price: 14,
    description: "Pierna de pollo broaster acompañada de salchicha dorada, ofreciendo una combinación crujiente, sabrosa y contundente.",
    badge: "PIERNA",
    popular: true,
    available: true,
    stock: 25,
    image: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00055",
    code: "PL00055",
    name: "Salchichorizo",
    category: "SALCHIPAPAS Y SALCHIBROASTERS",
    category_id: "C0010",
    price: 13,
    description: "Combinación de salchicha y chorizo dorados, preparada para ofrecer un sabor intenso y una textura deliciosa en cada bocado.",
    badge: "PARRILLERO",
    popular: false,
    available: true,
    stock: 30,
    image: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00056",
    code: "PL00056",
    name: "Salchipapa a lo Pobre",
    category: "SALCHIPAPAS Y SALCHIBROASTERS",
    category_id: "C0010",
    price: 13,
    description: "Una versión especial de la salchipapa con estilo casero, ideal para quienes buscan una opción abundante y llena de sabor.",
    badge: "A LO POBRE",
    popular: true,
    available: true,
    stock: 30,
    image: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  },
  {
    id: "PL00057",
    code: "PL00057",
    name: "Salchipapa Clásica",
    category: "SALCHIPAPAS Y SALCHIBROASTERS",
    category_id: "C0010",
    price: 10,
    description: "Salchicha dorada acompañada de papas crocantes, creando una combinación clásica, abundante y perfecta para compartir.",
    badge: "CLÁSICA",
    popular: true,
    available: true,
    stock: 40,
    image: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80",
    includes_sauces: true
  }
];

// List of Promotions for the promotions store matching the exact IDs
const promotions = [
  {
    id: "PL00042",
    title: "PROMO BROASTER FAMILIAR",
    price: 38,
    originalPrice: 44,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80",
    badge: "FAMILIAR",
    description: "La selección ideal para compartir en familia. Incluye un Broaster Presa Pecho, un Broaster Presa Pierna y un Broaster Presa Ala, con el sabor crujiente que nos caracteriza, más una Gaseosa Personal Inca Kola.",
    features: [
      "Papa crocante",
      "Ensalada fresca",
      "Arroz",
      "Gaseosa Personal Inca Kola"
    ]
  },
  {
    id: "PL00043",
    title: "PROMO BUCHI DUO",
    price: 22,
    originalPrice: 28,
    image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600&auto=format&fit=crop&q=80",
    badge: "DUO",
    description: "Una experiencia pensada para dos. Disfruta de dos Hamburguesas Tipo Clásica elaboradas con nuestra hamburguesa artesanal premium, acompañadas de dos Gaseosas Personales Pepsi.",
    features: [
      "Papa crocante",
      "Hamburguesa artesanal",
      "Ensalada fresca",
      "2 Gaseosas Personales Pepsi"
    ]
  },
  {
    id: "PL00044",
    title: "PROMO SALCHI BURGER",
    price: 24,
    originalPrice: 30,
    image: "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600&auto=format&fit=crop&q=80",
    badge: "COMBO",
    description: "La fusión de nuestros dos clásicos más pedidos. Una Hamburguesa Tipo Cheese Burguer y una Salchipapa Tipo Salchipapa Clásica, acompañadas de una Gaseosa Personal Coca Cola.",
    features: [
      "Queso cheddar",
      "Papa crocante",
      "Ensalada fresca",
      "Gaseosa Personal Coca Cola"
    ]
  },
  {
    id: "PL00045",
    title: "PROMO SELVA POWER",
    price: 29,
    originalPrice: 35,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80",
    badge: "SELVA",
    description: "Un homenaje a la Amazonía. Compuesto por un Plato Amazónico Tipo Tacacho con Cecina y un Salchibroaster Tipo Salchibroaster Pierna Presa Pierna, junto a una Gaseosa Personal Fanta.",
    features: [
      "Maduros fritos",
      "Sarza criolla",
      "Papa crocante",
      "Ensalada fresca",
      "Gaseosa Personal Fanta"
    ]
  }
];

// Perform regex replacements for products and promotions inside queries.ts
const startIdx = content.indexOf('const initialProducts: Product[] = [');
const endIdx = content.indexOf('];', startIdx) + 2;

if (startIdx !== -1 && endIdx > startIdx) {
  const replacementStr = `const initialProducts: Product[] = ${JSON.stringify(products, null, 2)};`;
  content = content.slice(0, startIdx) + replacementStr + content.slice(endIdx);
}

const startPromoIdx = content.indexOf('const initialPromotions: Promotion[] = [');
const endPromoIdx = content.indexOf('];', startPromoIdx) + 2;

if (startPromoIdx !== -1 && endPromoIdx > startPromoIdx) {
  const replacementPromoStr = `const initialPromotions: Promotion[] = ${JSON.stringify(promotions, null, 2)};`;
  content = content.slice(0, startPromoIdx) + replacementPromoStr + content.slice(endPromoIdx);
}

fs.writeFileSync(filePath, content, 'utf8');
console.log('Successfully updated product catalog with exact sequential IDs PL00001 to PL00057!');
